---
comments: false
title: "Licença"
editor: source
---

Meus [posts](/blog/), [palestras](/talk/) e [ensino](/teaching/) são distribuídos sob a licença [Creative Commons Attribution-ShareAlike 4.0 International License](http://creativecommons.org/licenses/by-sa/4.0/).

Você tem o direito de:

- Compartilhar — copiar e redistribuir o material em qualquer suporte ou formato para qualquer fim, mesmo que comercial.

- Adaptar — remixar, transformar, e criar a partir do material para qualquer fim, mesmo que comercial.

- O licenciante não pode revogar estes direitos desde que você respeite os termos da licença.

De acordo com os termos seguintes: 

- Atribuição — Você deve dar o crédito apropriado , prover um link para a licença e indicar se mudanças foram feitas. Você deve fazê-lo em qualquer circunstância razoável, mas de nenhuma maneira que sugira que o licenciante apoia você ou o seu uso.

- Compartilha Igual — Se você remixar, transformar, ou criar a partir do material, tem de distribuir as suas contribuições sob a mesma licença que o original.

- Sem restrições adicionais — Você não pode aplicar termos jurídicos ou medidas de caráter tecnológico que restrinjam legalmente outros de fazerem algo que a licença permita.

<br>

<center>{{< fa brands creative-commons size=2xl >}} {{< fa brands creative-commons-by size=2xl >}} {{< fa brands creative-commons-sa size=2xl >}}</center>
