# install packages
remotes::install_github("r-spatialecology/vectormetrics")

# packages
library(tidyverse)
library(sf)
library(vectormetrics)
library(tmap)

options(scipen = 1e3)

# data
data("vector_landscape")
vector_landscape
plot(vector_landscape)

# rio claro
download.file("https://geo.fbds.org.br/SP/RIO_CLARO/USO/SP_3543907_USO.dbf", "~/Downloads/SP_3543907_USO.dbf", mode = "wb")
download.file("https://geo.fbds.org.br/SP/RIO_CLARO/USO/SP_3543907_USO.prj", "~/Downloads/SP_3543907_USO.prj", mode = "wb")
download.file("https://geo.fbds.org.br/SP/RIO_CLARO/USO/SP_3543907_USO.shp", "~/Downloads/SP_3543907_USO.shp", mode = "wb")
download.file("https://geo.fbds.org.br/SP/RIO_CLARO/USO/SP_3543907_USO.shx", "~/Downloads/SP_3543907_USO.shx", mode = "wb")

vector_landscape <- sf::st_read("~/Downloads/SP_3543907_USO.shp") %>% 
    janitor::clean_names() %>% 
    dplyr::filter(classe_uso == "formação florestal") %>% 
    dplyr::rename(class = classe_uso) %>% 
    dplyr::select(class, area_ha, geometry)
vector_landscape

tm_shape(vector_landscape) +
    tm_fill(fill = "forestgreen")

# utilities
vector_patches <- vectormetrics::get_patches(vector_landscape, class_col = "class", direction = 4) %>%
  dplyr::mutate(patch = as.factor(patch))
vector_patches

tm_shape(vector_patches) +
    tm_fill(fill = "patch", legend.show = FALSE)

vector_axes <- vectormetrics::get_axes(vector_patches, class_col = "class")
vector_axes

# patch metrics
vectormetrics::vm_p_area(vector_landscape, class_col = "class")
vectormetrics::vm_p_cai(vector_landscape, class_col = "class", edge_depth = 30)
vectormetrics::vm_p_circ(vector_landscape, class_col = "class")
vectormetrics::vm_p_circle(vector_landscape, class_col = "class")
vectormetrics::vm_p_coh(vector_landscape, class_col = "class")
vectormetrics::vm_p_comp(vector_landscape, class_col = "class")
vectormetrics::vm_p_convex(vector_landscape, class_col = "class")
vectormetrics::vm_p_core(vector_landscape, class_col = "class", edge_depth = 1)
vectormetrics::vm_p_detour(vector_landscape, class_col = "class")
vectormetrics::vm_p_eac_perim(vector_landscape, class_col = "class")
vectormetrics::vm_p_elong(vector_landscape, class_col = "class")
vectormetrics::vm_p_enn(vector_landscape, class_col = "class")
vectormetrics::vm_p_eri(vector_landscape, class_col = "class")
vectormetrics::vm_p_exchange(vector_landscape, class_col = "class")
vectormetrics::vm_p_frac(vector_landscape, class_col = "class")
vectormetrics::vm_p_fullness(vector_landscape, class_col = "class")
vectormetrics::vm_p_girth(vector_landscape, class_col = "class")
vectormetrics::vm_p_hull_a(vector_landscape, class_col = "class")
vectormetrics::vm_p_hull_p(vector_landscape, class_col = "class")
vectormetrics::vm_p_ncore(vector_landscape, class_col = "class", edge_depth = 1)
vectormetrics::vm_p_perarea(vector_landscape, class_col = "class")
vectormetrics::vm_p_perim(vector_landscape, class_col = "class")
vectormetrics::vm_p_perim_idx(vector_landscape, class_col = "class")
vectormetrics::vm_p_proxim(vector_landscape, class_col = "class")
vectormetrics::vm_p_range(vector_landscape, class_col = "class")
vectormetrics::vm_p_rect(vector_landscape, class_col = "class")
vectormetrics::vm_p_rough(vector_landscape, class_col = "class")
vectormetrics::vm_p_shape(vector_landscape, class_col = "class")
vectormetrics::vm_p_solid(vector_landscape, class_col = "class")
vectormetrics::vm_p_sph(vector_landscape, class_col = "class")
vectormetrics::vm_p_square(vector_landscape, class_col = "class")

# class metrics
vectormetrics::vm_c_area_cv(vector_landscape, class_col = "class")
vectormetrics::vm_c_area_mn(vector_landscape, class_col = "class")
vectormetrics::vm_c_area_sd(vector_landscape, class_col = "class")
vectormetrics::vm_c_ca(vector_landscape, class_col = "class")
vectormetrics::vm_c_cai_cv(vector_landscape, class_col = "class", edge_depth = 30)
vectormetrics::vm_c_cai_mn(vector_landscape, class_col = "class", edge_depth = 30)
vectormetrics::vm_c_cai_sd(vector_landscape, class_col = "class", edge_depth = 30)
vectormetrics::vm_c_circ_mn(vector_landscape, class_col = "class")
vectormetrics::vm_c_circle_cv(vector_landscape, class_col = "class")
vectormetrics::vm_c_circle_mn(vector_landscape, class_col = "class")
vectormetrics::vm_c_circle_sd(vector_landscape, class_col = "class")
vectormetrics::vm_c_coh_mn(vector_landscape, class_col = "class")
vectormetrics::vm_c_comp_mn(vector_landscape, class_col = "class")
vectormetrics::vm_c_convex_mn(vector_landscape, class_col = "class")
vectormetrics::vm_c_core_cv(vector_landscape, class_col = "class")
vectormetrics::vm_c_core_mn(vector_landscape, class_col = "class")
vectormetrics::vm_c_core_sd(vector_landscape, class_col = "class")
vectormetrics::vm_c_cpland(vector_landscape, class_col = "class")
vectormetrics::vm_c_dcad(vector_landscape, class_col = "class")
vectormetrics::vm_c_dcore_cv(vector_landscape, class_col = "class")
vectormetrics::vm_c_dcore_mn(vector_landscape, class_col = "class")
vectormetrics::vm_c_dcore_sd(vector_landscape, class_col = "class")
vectormetrics::vm_c_detour_mn(vector_landscape, class_col = "class")
vectormetrics::vm_c_division(vector_landscape, class_col = "class")
vectormetrics::vm_c_ed(vector_landscape, class_col = "class")
vectormetrics::vm_c_elong_mn(vector_landscape, class_col = "class")
vectormetrics::vm_c_enn_cv(vector_landscape, class_col = "class")
vectormetrics::vm_c_enn_mn(vector_landscape, class_col = "class")
vectormetrics::vm_c_enn_sd(vector_landscape, class_col = "class")
vectormetrics::vm_c_eri_mn(vector_landscape, class_col = "class")
vectormetrics::vm_c_exchange_mn(vector_landscape, class_col = "class")
vectormetrics::vm_c_frac_cv(vector_landscape, class_col = "class")
vectormetrics::vm_c_frac_mn(vector_landscape, class_col = "class")
vectormetrics::vm_c_frac_sd(vector_landscape, class_col = "class")
vectormetrics::vm_c_fullness(vector_landscape, class_col = "class")
vectormetrics::vm_c_fullness_mn(vector_landscape, class_col = "class")
vectormetrics::vm_c_girth_mn(vector_landscape, class_col = "class")
vectormetrics::vm_c_lpi(vector_landscape, class_col = "class")
vectormetrics::vm_c_lsi(vector_landscape, class_col = "class")
vectormetrics::vm_c_mesh(vector_landscape, class_col = "class")
vectormetrics::vm_c_ndca(vector_landscape, class_col = "class")
vectormetrics::vm_c_np(vector_landscape, class_col = "class")
vectormetrics::vm_c_pd(vector_landscape, class_col = "class")
vectormetrics::vm_c_perarea_cv(vector_landscape, class_col = "class")
vectormetrics::vm_c_perarea_mn(vector_landscape, class_col = "class")
vectormetrics::vm_c_perarea_sd(vector_landscape, class_col = "class")
vectormetrics::vm_c_perim_idx_mn(vector_landscape, class_col = "class")
vectormetrics::vm_c_pland(vector_landscape, class_col = "class")
vectormetrics::vm_c_proxim_mn(vector_landscape, class_col = "class")
vectormetrics::vm_c_range_mn(vector_landscape, class_col = "class")
vectormetrics::vm_c_rect_mn(vector_landscape, class_col = "class")
vectormetrics::vm_c_rough_mn(vector_landscape, class_col = "class")
vectormetrics::vm_c_shape_cv(vector_landscape, class_col = "class")
vectormetrics::vm_c_shape_mn(vector_landscape, class_col = "class")
vectormetrics::vm_c_shape_sp(vector_landscape, class_col = "class")
vectormetrics::vm_c_solid_mn(vector_landscape, class_col = "class")
vectormetrics::vm_c_sph_mn(vector_landscape, class_col = "class")
vectormetrics::vm_c_split(vector_landscape, class_col = "class")
vectormetrics::vm_c_square_mn(vector_landscape, class_col = "class")
vectormetrics::vm_c_tca(vector_landscape, class_col = "class")
vectormetrics::vm_c_te(vector_landscape, class_col = "class")

# landscape metrics
vectormetrics::vm_l_area_mn(vector_landscape)
vectormetrics::vm_l_cai_mn(vector_landscape)
vectormetrics::vm_l_circ_mn(vector_landscape)
vectormetrics::vm_l_coh_mn(vector_landscape)
vectormetrics::vm_l_comp_mn(vector_landscape)
vectormetrics::vm_l_convex_mn(vector_landscape)
vectormetrics::vm_l_core_mn(vector_landscape)
vectormetrics::vm_l_dcad(vector_landscape)
vectormetrics::vm_l_dcore_mn(vector_landscape)
vectormetrics::vm_l_detour_mn(vector_landscape)
vectormetrics::vm_l_division(vector_landscape)
vectormetrics::vm_l_ed(vector_landscape)
vectormetrics::vm_l_ed(vector_landscape)
vectormetrics::vm_l_elong_mn(vector_landscape)
vectormetrics::vm_l_eri_mn(vector_landscape)
vectormetrics::vm_l_exchange_mn(vector_landscape)
vectormetrics::vm_l_frac_mn(vector_landscape)
vectormetrics::vm_l_fullness(vector_landscape)
vectormetrics::vm_l_fullness_mn(vector_landscape)
vectormetrics::vm_l_girth_mn(vector_landscape)
vectormetrics::vm_l_lpi(vector_landscape)
vectormetrics::vm_l_lsi(vector_landscape, edge_depth = 1)
vectormetrics::vm_l_mesh(vector_landscape)
vectormetrics::vm_l_msidi(vector_landscape)
vectormetrics::vm_l_msiei(vector_landscape)
vectormetrics::vm_l_ndca(vector_landscape)
vectormetrics::vm_l_np(vector_landscape)
vectormetrics::vm_l_pafrac(vector_landscape)
vectormetrics::vm_l_pd(vector_landscape)
vectormetrics::vm_l_perarea_mn(vector_landscape)
vectormetrics::vm_l_perim_idx_mn(vector_landscape)
vectormetrics::vm_l_pr(vector_landscape)
vectormetrics::vm_l_prd(vector_landscape)
vectormetrics::vm_l_proxim_mn(vector_landscape)
vectormetrics::vm_l_range_mn(vector_landscape)
vectormetrics::vm_l_rect_mn(vector_landscape)
vectormetrics::vm_l_rough_mn(vector_landscape)
vectormetrics::vm_l_rpr(vector_landscape)
vectormetrics::vm_l_shape_mn(vector_landscape)
vectormetrics::vm_l_shdi(vector_landscape)
vectormetrics::vm_l_shei(vector_landscape)
vectormetrics::vm_l_sidi(vector_landscape)
vectormetrics::vm_l_siei(vector_landscape)
vectormetrics::vm_l_solid_mn(vector_landscape)
vectormetrics::vm_l_sph_mn(vector_landscape)
vectormetrics::vm_l_split(vector_landscape)
vectormetrics::vm_l_square_mn(vector_landscape)
vectormetrics::vm_l_ta(vector_landscape)
vectormetrics::vm_l_tca(vector_landscape)
vectormetrics::vm_l_te(vector_landscape)

# end ---------------------------------------------------------------------
