---
title: "Publicações"
subtitle: "Publicações acadêmicas, científicas e divulgações na mídia."
page-layout: full
title-block-banner: false
toc: true
editor: source
---

## Artigos

1. Beca, G., <u>**Vancine, M. H.**</u>, Carvalho, C. S., Pedrosa, F., Alves, R. S. C., Buscariol, D., ... & Galetti, M. (2017). [High mammal species turnover in forest patches immersed in biofuel plantations](/publication/2017-beca-etal){target="_blank"}. *Biological Conservation*, 210, 352-359.

1. de Castro Pena, J. C., Goulart, F., Fernandes, G. W., Hoffmann, D., Leite, F. S., dos Santos, N. B., Soares-Filho, B., Sobral-Souza, T., <u>**Vancine, M. H.**</u>, & Rodrigues, M. (2017). [Impacts of mining activities on the potential geographic distribution of eastern Brazil mountaintop endemic species](/publication/2017-pena-etal){target="_blank"}. *Perspectives in Ecology and Conservation*, 15(3), 172-178.

1. Regolin, A. L., Cherem, J. J., Graipel, M. E., Bogoni, J. A., Ribeiro, J. W., <u>**Vancine, M. H.**</u>, ... & Castilho, P. V. D. (2017). [Forest cover influences occurrence of mammalian carnivores within Brazilian Atlantic Forest](/publication/2017-regolin-etal){target="_blank"}. *Journal of Mammalogy*, 98(6), 1721-1731.

1. Sobral-Souza, T., <u>**Vancine, M. H.**</u>, Ribeiro, M. C., & Lima-Ribeiro, M. S. (2018). [Efficiency of protected areas in Amazon and Atlantic Forest conservation: A spatio-temporal view](/publication/2018-sobral-souza-etal){target="_blank"}. *Acta Oecologica*, 87, 1-7.

1. Muylaert, R. L., <u>**Vancine, M. H.**</u>, Bernardo, R., Oshima, J. E. F., Sobral-Souza, T., Tonetti, V. R., ... & Ribeiro, M. C. (2018). [A note on the territorial limits of the Atlantic Forest](/publication/2018-muylaert-etal){target="_blank"}. *Oecologia Australis*, 22(3), 302-311.

1. <u>**Vancine, M. H.**</u>, Duarte, K. D. S., de Souza, Y. S., Giovanelli, J. G. R., Martins‐Sobrinho, P. M., López, A., ... & Brassaloti, R. (2018). [ATLANTIC AMPHIBIANS: a data set of amphibian communities from the Atlantic Forests of South America](/publication/2018-vancine-etal){target="_blank"}. *Ecology*, 99(7), 1692-1692.

1. Ferro e Silva, A. M., Sobral-Souza, T., <u>**Vancine, M. H.**</u>, Muylaert, R. L., de Abreu, A. P., Pelloso, S. M., ... & de Ornelas Toledo, M. J. (2018). [Spatial prediction of risk areas for vector transmission of Trypanosoma cruzi in theState of Paraná, southern Brazil](/publication/2018-ferro-e-silva-etal){target="_blank"}. *PLoS Neglected Tropical Diseases*, 12(10), e0006907.

1. Bertassoni, A., Costa, R. T., Gouvea, J. A., Bianchi, R. D. C., Ribeiro, J. W., <u>**Vancine, M. H.**</u>, & Ribeiro, M. C. (2019). [Land-use changes and the expansion of biofuel crops threaten the giant anteater in southeastern Brazil](/publication/2019-bertassoni-etal){target="_blank"}. *Journal of Mammalogy*, 100(2), 435-444.

1. Moraes, A. M., <u>**Vancine, M. H.**</u>, Moraes, A. M., de Oliveira Cordeiro, C. L., Pinto, M. P., Lima, A. A., ... & Sobral-Souza, T. (2019). [Predicting the potential hybridization zones between native and invasive marmosets within Neotropical biodiversity hotspots](/publication/2019-moraes-etal){target="_blank"}. *Global Ecology and Conservation*, 20, e00706.06.

1. Santos, J. P., Sobral‐Souza, T., Brown Jr, K. S., <u>**Vancine, M. H.**</u>, Ribeiro, M. C., & Freitas, A. V. (2020). [Effects of landscape modification on species richness patterns of fruit‐feeding butterflies in Brazilian Atlantic Forest](/publication/2020-santos-etal){target="_blank"}. *Diversity and Distributions*, 26(2), 196-208.

1. Marjakangas, E. L., Abrego, N., Grøtan, V., de Lima, R. A., Bello, C., Bovendorp, R. S., Culot, L., Hasui, E., Lima, F., Muylaert, R. L., Niebuhr, B. B., Oliveira, A. A., Pereira, L. A., Prado, P. I., Stevens, R. D., <u>**Vancine, M. H.**</u>, Ribeiro, M. C., Galetti, M., & Ovaskainen, O. (2020). [Fragmented tropical forests lose mutualistic plant–animal interactions](/publication/2020-marjakangas-etal){target="_blank"}. *Diversity and Distributions*, 26(2), 154-168.

1. Bello, C., Cintra, A. L. P., Barreto, E., <u>**Vancine, M. H.**</u>, Sobral-Souza, T., Graham, C. H., & Galetti, M. (2021). [Environmental niche and functional role similarity between invasive and native palms in the Atlantic Forest](/publication/2021-bello-etal){target="_blank"}. *Biological Invasions*, 23(3), 741-754.

1. Gusmão, R. A., Hernandes, F. A., <u>**Vancine, M. H.**</u>, Naka, L. N., Doña, J., & Gonçalves‐Souza, T. (2021). [Host diversity outperforms climate as a global driver of symbiont diversity in the bird‐feather mite system](/publication/2021-gusmao-etal){target="_blank"}. *Diversity and Distributions*,27(3), 416-426.

1. Da Silveira, N. S., <u>**Vancine, M. H.**</u>, Jahn, A. E., Pizo, M. A., & Sobral-Souza, T. (2021). [Future climate change will impact the size and location of breeding and wintering areas of migratory thrushes in South America](/publication/2021-da-silveira-etal){target="_blank"}. *The Condor*, 123(2), duab006.

1. Jover, A., Cabrera, A., Ramos, A., <u>**Vancine, M. H.**</u>, Suárez, A. M., Machell, J., & Pérez-Lloréns, J. L. (2021). [Distribution of macroalgae epiphytes and host species from the Cuban marine shelf inferred from ecological modelling](/publication/2021-jover-etal){target="_blank"}. *Aquatic Botany*, 172, 103395.

1. Bercê, W., Bello, C., Mendes, C. P., <u>**Vancine, M. H.**</u>, Galetti, M., & Ballari, S. A. (2021). [Invasive wild boar’s distribution overlap with threatened native ungulate in Patagonia](/publication/2021-berce-etal){target="_blank"}. *Journal of Mammalogy*, 102(5), 1298-1308.

1. Oshima, J. E. F., Jorge, M. L. S., Sobral-Souza, T., Börger, L., Keuroghlian, A., Peres, C. A., <u>**Vancine, M. H.**</u>, Colleni, B., & Ribeiro, M. C. (2021). [Setting priority conservation management regions to reverse rapid range decline of a key neotropical forest ungulate](/publication/2021-oshima-etal){target="_blank"}. *Global Ecology and Conservation*, 31, e01796.

1. Monteiro, E. C., Pizo, M. A., <u>**Vancine, M. H.**</u>, & Ribeiro, M. C. (2022). [Forest cover and connectivity have pervasive effects on the maintenance of evolutionary distinct interactions in seed dispersal networks](/publication/2022-monteiro-etal){target="_blank"}. *Oikos*, 2022(2), oik.08240.

1. Ribeiro-Souza, P., Graipel, M. E., Astúa, D., <u>**Vancine, M. H.**</u>, & Pires, J. S. R. (2022). [Effects of climate change on distribution and areas that protect two neotropical marsupials associated with aquatic environments](/publication/2022-ribeiro-souza-etal){target="_blank"}. *Ecological Informatics*, 68, 101570.

1. Costa, M. F., Francisconi, A. F., <u>**Vancine, M. H.**</u>, & Zucchi, M. I. (2022). [Climate change impacts on the Copernicia alba and Copernicia prunifera (Arecaceae) distribution in South America](/publication/2022-costa-etal). *Brazilian Journal of Botany*, 45, 807–818.

1. Muylaert, R. L., Kingston, T., Luo, J., <u>**Vancine, M. H.**</u>, Galli, N., Carlson, C. J., ... & Hayman, D. T. (2022). [Present and future distribution of bat hosts of sarbecoviruses: implications for conservation and public health](/publication/2022-muylaert-etal){target="_blank"}. *Proceedings of the Royal Society B*, 289(1975), 20220397.

1. Borges, G. A., Mancilla, G., Siqueira, A. B., <u>**Vancine, M. H.**</u>, Ribeiro, M. C., & Maia, J. C. S. (2022). [The fate of vegetation remnants in the southern Amazon's largest threatened hotspot: part (I) a 33-year analysis of LULCC in the Tapajos River basin, Brazil](/publication/2022-borges-etal){target="_blank"}. *Research, Society and Development*, 11(10), e448111032553.

1. Galetti, M., Carmignotto, A. P., Percequillo, A. R., Santos, M. C. de O., Ferraz, K. M. P. M. de B., Lima, F., <u>**Vancine, M. H.**</u>, Muylaert, R. L., Bonfim, F. C. G., Magioli, M., Abra, F. D., Chiarello, A. G., Duarte, J. M. B., Morato, R., de Mello Beisiegel, B., Olmos, F., Galetti Jr., P. M., & Ribeiro, M. C. (2022). [Mammals in São Paulo State: diversity, distribution, ecology, and conservation](/publication/2022-galetti-etal){target="_blank"}. *Biota Neotropica*, 22(spe), e20221363. 

1. Santos, P. M., Ferraz, K. M. P. M. B., Ribeiro, M. C., Niebuhr, B. B., <u>**Vancine, M. H.**</u>, Chiarello, A. C., & Paglia, A. P. (2022). [Natural forest regeneration on anthropized landscapes could overcome climate change effects on the endangered maned sloth (Bradypus torquatus, Illiger 1811)](/publication/2022-santos-etal){target="_blank"}. *Journal of Mammology*, 103(6), 1383-1396.

1. Dutra, V. A. B., <u>**Vancine, M. H.**</u>, Lima, A. A. M., & Toledo, P. M. (2023). [Dinâmica da paisagem e fragmentação de ecossistemas em três bacias hidrográficas na Amazônia Oriental entre 1985 e 2019](/publication/2023-dutra-etal){target="_blank"}. *Revista Brasileira de Geografia Física*, 16(02), 936-949.

1. Amaral, I. S., Pereira, J. B., <u>**Vancine, M. H.**</u>, Morales, A. E., Althoff, S. L., Gregorin, R., Pereira, M. J. R., Valiali, V. H., & Oliveira, L. R. (2023). [Where do they live? Predictive geographic distribution of Tadarida brasiliensis brasiliensis (Chiroptera, Molossidae) in South America](/publication/2023-amaral-etal){target="_blank"}. *Neotropical Biology and Conservation*, 18(3), 139-156. 

1. Anunciação, P. A., Ernst, R., Martello, F., <u>**Vancine, M. H.**</u>, Ribeiro, M. C., & Carvalho, L. M. T. (2023). [Climate driven loss of taxonomic and functional richness in Atlantic Forest anurans](/publication/2023-anunciacao-etal){target="_blank"}. *Perspectives in Ecology and Conservation*, 21(4), 274-285.

1. Teixeira, J. V. S., Bonfim, F. C. G., <u>**Vancine, M. H.**</u>, Ribeiro, M. C., & Oliveira, L. C. (2023). [Effect of landscape attributes at multiple scales on the occurrence of the threatened golden-headed lion tamarin Leontopithecus chrysomelas Kuhl, 1820 (Primates, Callitrichidae)](/publication/2023-teixeira-etal){target="_blank"}. *American Journal of Primatology*, 86(4), e23588.

1. Tonetti, V., Bocalini, F., Schunck, F., <u>**Vancine, M. H.**</u>, Butti, M., Ribeiro, M. C., Pizo, M., & Balmford, A. (2024). [The Protected Areas network may be inefficient to cover biodiversity in a fragmented tropical hotspot under different climate scenarios](/publication/2024-tonetti-etal){target="_blank"}. *Perspectives in Ecology and Conservation*, 22(1), 63-71.

1. <u>**Vancine, M. H.**</u>, Muylaert, R. L., Niebuhr, B. B., Oshima, J. E. F., Tonetti, V., Bernardo, R., De Angelo, C., Rosa, M. R., Grohmann C. H., & Ribeiro, M. C. (2024). [The Atlantic Forest of South America: spatiotemporal dynamics of vegetation and implications for conservation](/publication/2024-vancine-etal){target="_blank"}. *Biological Conservation*, 291, 110499.

1. Barbosa, F. S., <u>**Vancine, M. H.**</u>, Ribeiro, M. C. & Siminski, A. (2024). [Análise espacial da fragmentação da paisagem: um estudo de caso sobre os fragmentos forestais destinados à Reserva Legal em duas bacias hidrográfcas no Estado do Piauí](/publication/2024-barbosa-etal){target="_blank"}. *Revista Observatório de la Economía Latinoamericana*, 22(11), e7996.

1. Marques, R. C. M., <u>**Vancine, M. H.**</u>, Súarez, Y. R., Pereira, J. G., Domingos, J. D., Silva, A. B. B., Pereira, Z. V. (2024). [Dinâmica espaço temporal: variações na composição e configuração da vegetação](/publication/2025-marques-etal){target="_blank"}. *Revista Brasileira de Geografia Física*, 18(2), 1334-1348.

1. Carvalho, T., Falconi, N., White, T., Anjos, L. A., Giasson, L. O. M., <u>**Vancine, M. H.**</u>, Haddad, C. F. B., Toledo, L. F., Becker, C. G. (2025). [The role of seasonal migration in predicting amphibian population persistence across fragmented tropical landscapes: an Individual-Based Model](/publication/2025-carvalho-etal){target="_blank"}. *Biodiversity and Conservation*, 34, 1291-1310.

1. Gonçalves-Souza, T., <u>**Vancine, M. H.**</u>, Sanders, N. J., Haddad, N. M., (…), Chase, J. M. (2025). [LandFrag: a dataset to investigate the effects of habitat loss and fragmentation on biodiversity in forest fragments](/publication/2025-goncalves-souza-vancine-etal){target="_blank"}. *Global Ecology and Biogeography (Data Article)*, 34(2):e70015.

1. Gonçalves-Souza, T., Chase, J., Haddad, N., <u>**Vancine, M. H.**</u>, Melo, F. P. L., Aizen, M., Bernard, E., Chiarello, G. A., Didham, R., Faria, D., Gibb, H., Lima, M., Magnago, L., Mariano Neto, E., Nogueira, A., Nemésio, A., Passamani, M., Pinho, B. X., Rocha-Santos, L., Rodrigues, R., Safar, N., Santos, B., Soto-Werschitz, A., Tabarelli, M., Uehara-Prado, M., Vasconcelos, H., Vieira, S., Sanders, N. (2025). [Species turnover does not rescue biodiversity in fragmented landscapes](/publication/2025-goncalves-souza-etal){target="_blank"}. *Nature*, 640, 702-706.

1. Alves-Ferreira, G., <u>**Vancine, M. H.**</u>, Mota, F. M. M., Bello, C., Sobral-Souza, T., Percequillo, A. R., Lacher Jr., T. E., Galetti, M., Bovendorp, R. S. (2025). [From hot to cold spots: climate change will modify endemism centers of small mammals in a biodiversity hotspot](/publication/2025-alves-ferreira-vancine-etal){target="_blank"}. *Diversity and Distributions*, 31(5), e70026. 

1. Goebel, L. G. A, <u>**Vancine, M. H.**</u>, Bogoni, J. A., Longo, G. R., Calicis, M., Fearside, P. M., Palmeirim, A. F., Santos-Filho, M. (2025). [The impact of Amazon deforestation is magnified by changing the configuration of forest cover](/publication/2025-goebel-etal){target="_blank"}. *Environmental Conservation*. *in press*.

1. da Silva, R. F. B., Millington, J. D. A., Yue, D., <u>**Vancine, M. H.**</u>, Magnago, L. F. S., Viña, A., Bin, F., Huesca, M., Viera, S. A., Garibaldi, L. A., Liu, J. (2025). [Secondary natural vegetation gains in the Atlantic Forest do not offset losses of carbon stocks and conservation of priority areas](/publication/2025-da-silva-etal){target="_blank"}. *Biological Conservation*, 312, 111512.

1. Gonçalves-Souza, T., <u>**Vancine, M. H.**</u>, Paterno, G. B. (2025). [Computer vision uncovers trait-based insect responses to habitat loss](/publication/2025-goncalves-souza-vancine-paterno){target="_blank"}. *Journal of Animal Ecology*, doi: 10.1111/1365-2656.70165.

## Livros

1. Da Silva, F. R., Gonçalves-Souza, T., Paterno, G. B., Provete, D. B., & <u>**Vancine, M. H.**</u> (2022). [Análises Ecológicas no R](/publication/2022-da-silva-etal){target="_blank"}. *Recife: Nupeea; Bauru, SP: Canal 6*. ISBN 978-85-7917-563-3.

## Preprints

1. <u>**Vancine, M. H.**</u>, Muylaert, R. L., Niebuhr, B. B., Oshima, J. E. F., Tonetti, V., Bernardo, R., De Angelo, C., Rosa, M. R., Grohmann C. H., & Ribeiro, M. C. (2023). [The Atlantic Forest of South America: spatiotemporal dynamics of vegetation and implications for conservation](/publication/2023a-vancine-etal){target="_blank"}. *bioRxiv*. DOI: https://doi.org/10.1101/2023.09.16.558076.

1. <u>**Vancine, M. H.**</u>, Niebuhr B. B., Muylaert R. L., Oshima J. E. F., Tonetti V., Bernardo R., Alves R. S. C., Zanette E. M., Souza V. C., Giovanelli J. G. R., Grohmann C. H., Galetti M., & Ribeiro, M. C. (2023). [ATLANTIC SPATIAL: a data set of landscape, topographic, hydrological and anthropogenic metrics for the Atlantic Forest](/publication/2023b-vancine-etal){target="_blank"}. *EcoEvoRxiv*. DOI: https://doi.org/10.32942/X26P58.

## Acadêmicas

1. <u>**Vancine, M. H.**</u> (2015). [Efeito da fragmentação sobre a persistência de anfíbios anuros (Amphibia: Anura) na Mata Atlântica](/publication/2015-vancine){target="_blank"}. *Universidade Estadual Paulista, Instituto de Biociências de Rio Claro*.

1. Lauretto L.T. (2017). [Planejamento sistemático de conservação no contexto do projeto BIOTA/FAPESP](/publication/2017-lauretto){target="_blank"}. *Universidade Estadual Paulista, Instituto de Biociências de Rio Claro*. [Coorientador]

1. <u>**Vancine, M. H.**</u> (2018). [Diversidade, distribuição e efeito das mudanças climáticas sobre comunidades de anfíbios da Mata Atlântica](/publication/2018-vancine){target="_blank"}. *Universidade Estadual Paulista, Instituto de Biociências de Rio Claro*.

1. Almeida, L. S. (2019). [Modelagem da distribuição das Cecílias (Amphibia: Gymnophiona) do Brasil: subsídios para conservação e amostragens de campo](/publication/2019-almeida){target="_blank"}. *Universidade Estadual Paulista, Instituto de Biociências de Rio Claro*. [Coorientador]

1. Oliveira, H. T. C. (2021). [Distribuição do padrão reprodutivo em comunidades de anuros na Mata Atlântica](/publication/2021-oliveira){target="_blank"}. *Universidade Estadual Paulista, Instituto de Biociências de Rio Claro*. [Orientador]

1. Silva, B. E. R. (2022). [Comparação da distribuição de espécies inferidos por modelos de nicho ecológicos e mapas de especialistas da IUCN para anfíbios anuros da América do Sul](/publication/2022-silva){target="_blank"}. *Universidade Estadual Paulista, Instituto de Biociências de Rio Claro*. [Orientador]

1. Almeida, L. S. (2022). [Conhecimento atual, distribuição potencial e conservação de cecílias (Amphibia: Gymnophiona) na Região Neotropical](/publication/2022-almeida){target="_blank"}. *Universidade Estadual Paulista, Instituto de Biociências de Rio Claro*. [Coorientador]

1. <u>**Vancine, M. H.**</u> (2024). [Estrutura da paisagem como preditor da diversidade taxonômica e funcional de anfíbios na Mata Atlântica](/publication/2024-vancine){target="_blank"}. *Universidade Estadual Paulista, Instituto de Biociências de Rio Claro*.

## Mídia

1. [Grupo da Unesp divulga censo de mamíferos em florestas imersas na cana-de-açúcar](https://agencia.fapesp.br/grupo-da-unesp-divulga-censo-de-mamiferos-em-florestas-imersas-na-cana-de-acucar/24893/){target="_blank"}. (2017). Agência FAPESP.

1. [A fauna que sobrevive nas florestas nas plantações de cana](https://www2.unesp.br/portal#!/noticia/25866/a-fauna-que-sobrevive-nas-florestas-nas-plantacoes-de-cana/){target="_blank"}. (2017). Assessoria de Comunicação e Imprensa (ACI) Unesp.

1. [Census shows which mammals survive in forests surrounded by sugarcane plantations](https://phys.org/news/2017-06-census-mammals-survive-forests-sugarcane.html){target="_blank"}. (2017). Phys.ORG.

1. [Scientists hark back to Pleistocene to trace prioritary areas for conservation](https://phys.org/news/2018-05-scientists-hark-pleistocene-prioritary-areas.html){target="_blank"}. (2018). Phys.ORG.

1. [Pleistocene climates help scientists pick out targets for conservation in Brazil’s forests](https://news.mongabay.com/2018/05/pleistocene-climates-help-scientists-pick-out-targets-for-conservation-in-brazils-forests/?alm_mvr=0){target="_blank"}. (2018). Mongabay.

1. [El pasado da pistas sobre qué regiones pueden ser las más afectadas por los cambios climáticos](http://www.madrimasd.org/notiweb/noticias/pasado-da-pistas-sobre-que-regiones-pueden-ser-las-mas-afectadas-por-los-cambios-climaticos){target="_blank"}. (2018). Madrimasd.

1. [Redescobrindo os limites da Mata Atlântica](https://www2.unesp.br/portal#!/noticia/33763/redescobrindo-os-limites-da-mata-atlantica){target="_blank"}. (2018). Assessoria de Comunicação e Imprensa (ACI) Unesp.

1. [Nova visão sobre a eficiência das Unidades de Conservação](https://www2.unesp.br/portal#!/noticia/31669/nova-visao-sobre-a-eficiencia-das-unidades-de-conservacao){target="_blank"}. (2018). Assessoria de Comunicação e Imprensa (ACI) Unesp.

1. [Prioridade para conservação com olho no passado](https://agencia.fapesp.br/prioridade-para-conservacao-com-olho-no-passado/27579){target="_blank"}. (2018). Agência FAPESP.

1. [Os possíveis abrigos da doença de Chagas](/pdf/2018-muylaert-chagas.pdf){target="_blank"}. (2019). Unesp Ciência.

1. [Trees struggle when forests become too small](https://norwegianscitechnews.com/2020/01/trees-struggle-when-forests-become-too-small/){target="_blank"}. (2020). Norwegian SciTech News.

1. [Trees struggle when forests become too small](https://www.eurekalert.org/news-releases/715080){target="_blank"}. (2020). EurekAlert.

1. [Trees struggle when forests become too small](https://phys.org/news/2020-01-trees-struggle-forests-small.html){target="_blank"}. (2020). Phys.ORG.

1. [Trees struggle when forests become too small](https://bioengineer.org/trees-struggle-when-forests-become-too-small/){target="_blank"}. (2020). Bioengineer.ORG.

1. [Mapeamento de borboletas na Mata Atlântica identifica áreas prioritárias para conservação](https://agencia.fapesp.br/mapeamento-de-borboletas-na-mata-atlantica-identifica-areas-prioritarias-para-conservacao/33364/){target="_blank"}. (2020). Agência FAPESP.

1. [Borboletas como indicadoras da conservação da Mata Atlântica](https://www.terra.com.br/noticias/climatempo/borboletas-como-indicadoras-da-conservacao-da-mata-atlantica,991bd3e593d17c3476422f3d6fc13e69ao7tu19a.html){target="_blank"}. (2020). Terra.

1. [El mapeo de las mariposas en el Bosque Atlántico determina las áreas prioritarias de conservación](https://www.dicyt.com/noticias/el-mapeo-de-las-mariposas-en-el-bosque-atlantico-determina-las-areas-prioritarias-de-conservacion){target="_blank"}. (2021). Agência de Notícias para a Difusão da Ciência e Tecnologia (DiCYT).

1. [How will migratory birds in South America adapt to future climate change?](https://americanornithology.org/how-will-migratory-birds-in-south-america-adapt-to-future-climate-change/){target="_blank"}. (2021). American Ornithology Society.

1. [Estudo aponta impactos climáticos sobre aves migratórias na América do Sul](https://jornal.unesp.br/2021/08/20/estudo-aponta-impactos-climaticos-sobre-aves-migratorias-na-america-do-sul/){target="_blank"}. (2021). Jornal da Unesp.

1. [Sabiás viajantes e as mudanças climáticas](https://faunanews.com.br/sabias-viajantes-e-as-mudancas-climaticas/){target="_blank"}. (2021). FaunaNews.

1. [Study shows climate impacts on migratory birds in South America](https://www.international.unesp.br/sharer.php?noticia=163){target="_blank"}. (2021). UNESP Notícias.

1. [Forest cover and connectivity impact seed dispersal networks](https://conservationcorridor.org/digests/2021/09/forest-cover-and-connectivity-impact-seed-dispersal-networks/){target="_blank"}. (2021). Conservation Corridors.

1. [Grupo de pesquisadores lança livro gratuito sobre análise de dados ecológicos](http://www.ufrpe.br/br/content/grupo-de-pesquisadores-lan%C3%A7a-livro-gratuito-sobre-an%C3%A1lise-de-dados-ecol%C3%B3gicos){target="_blank"}. (2022). Universidade Federal Rural de Pernambuco.

1. [Pesquisadores lançam livro sobre análise de dados ecológicos](https://www.ufscar.br/noticia?codigo=14609){target="_blank"}. (2022). Ufscar.

1. [Notícias Rádio UFSCar #10](https://www.radio.ufscar.br/podcast/noticiasradioufscar-27-05-2022/){target="_blank"}. (2022). Ufscar.

1. [Mapping hotspots for bats may help scientists prepare for future bat-to-human viral outbreaks](https://www.massey.ac.nz/about/news/mapping-hotspots-for-bats-may-help-scientists-prepare-for-future-bat-to-human-viral-outbreaks/){target="_blank"}. (2022). Massey University.

1. [Predicting bat host hotspots to help prepare for future coronavirus outbreaks](https://www.scimex.org/newsfeed/predicting-bat-host-hotspots-helps-to-prepare-for-future-coronavirus-outbreaks){target="_blank"}. (2022). Scimex.

1. [Predicting bat host hotspots to help prepare for future coronavirus outbreaks](https://phys.org/news/2022-05-host-hotspots-future-coronavirus-outbreaks.html){target="_blank"}. (2022). Phys.ORG.

1. [Pesquisadores mapeiam áreas com potencial para futuros surtos de doenças semelhantes à Covid-19](https://jornal.unesp.br/2022/06/23/pesquisadores-mapeiam-areas-com-potencial-para-futuros-surtos-de-doencas-semelhantes-a-covid-19/){target="_blank"}. (2022). Jornal da Unesp.

1. [Pesquisadores mapeiam areas com potencial para futuros surtos de doencas virais](https://ciencianarua.net/pesquisadores-mapeiam-areas-com-potencial-para-futuros-surtos-de-doencas-virais){target="_blank"}. (2022). por Ciência na Rua.

1. [Preguiça-de-coleira-do-sudeste, espécie recém-descrita, pode perder 7 mil km² de sua área, caso florestas onde vive não sejam protegidas](https://conexaoplaneta.com.br/blog/preguica-de-coleira-do-sudeste-especie-recem-descrita-pode-perder-7-mil-km%C2%B2-de-sua-area-caso-florestas-onde-vive-nao-sejam-protegidas/){target="_blank"}. (2022). Conexão Planeta.

1. [Preguiças-de-coleira sob ameaça iminente](https://cienciahoje.org.br/artigo/preguicas-de-coleira-sob-ameaca-iminente/). (2023). [PDF](/pdf/2023-santos-etal.pdf){target="_blank"}. Ciência Hoje.

1. [Em quatro anos, Alto Tietê somou mais de 30 hectares desmatados](https://g1.globo.com/sp/mogi-das-cruzes-suzano/noticia/2023/06/05/em-quatro-anos-alto-tiete-somou-mais-de-30-hectares-desmatados.ghtml){target="_blank"}. (2023). g1 Mogi das Cruzes e Suzano.

1. [Global climate change, economic interests negatively impact amphibian diversity in Brazilian rainforest: Study](https://phys.org/news/2023-10-global-climate-economic-negatively-impact.html){target="_blank"}. (2023). Phys.org.

1. [Novo estudo destaca preocupação com estado de conservação da Mata Atlântica](https://jornal.unesp.br/2024/03/15/novo-estudo-destaca-preocupacao-com-estado-de-conservacao-da-mata-atlantica/){target="_blank"}. (2024). Jornal da UNESP.

1. [Novo estudo destaca preocupação com estado de conservação da Mata Atlântica](https://agencia.fapesp.br/novo-estudo-destaca-preocupacao-com-estado-de-conservacao-da-mata-atlantica/52013){target="_blank"}. (2024). Agência FAPESP.

1. [Novo estudo destaca preocupação com estado de conservação da mata atlântica](https://www1.folha.uol.com.br/folha-social-mais/2024/06/novo-estudo-destaca-preocupacao-com-estado-de-conservacao-da-mata-atlantica.shtml?utm_campaign=na_midia__n_23_junho_2024&utm_medium=email&utm_source=RD+Station){target="_blank"}. (2024). Folha de São Paulo.

1. [Novo estudo destaca preocupação com estado de conservação da Mata Atlântica](https://umsoplaneta.globo.com/biodiversidade/noticia/2024/06/24/novo-estudo-destaca-preocupacao-com-estado-de-conservacao-da-mata-atlantica.ghtml?utm_campaign=na_midia__n_23_junho_2024&utm_medium=email&utm_source=RD+Station). (2024). Um Só Planeta.

1. [Pesquisa da Unesp aponta melhora na conservação da Mata Atlântica](https://recordtv.r7.com/recordtv-interior-sp/sp-record/pesquisa-da-unesp-aponta-melhora-na-conservacao-da-mata-atlantica-27032024?utm_source=link_direto&utm_medium=share-bar&utm_campaign=r7-topo){target="_blank"}. (2024). RecordTV Interior SP.

1. [Unidades de Conservação: guardiãs da Mata Atlântica](https://www.ekosbrasil.org/unidades-de-conservacao-guardias-da-mata-atlantica){target="_blank"}. (2024). Ekos Brasil.

1. [About 97% of the Atlantic Forest consists of parts smaller than 50 hectares](https://www.wwf.org.br/?88703/About-97-of-the-Atlantic-Forest-consists-of-parts-smaller-than-50-hectares){target="_blank"}. (2024). WWF.

1. [Condomínios, estradas e caça: Mata Atlântica enfrenta novos riscos](https://olhardigital.com.br/2024/06/25/ciencia-e-espaco/condominios-estradas-e-caca-mata-atlantica-enfrenta-novos-riscos/){target="_blank"}. (2024). Olhar Digital [Ciência e Espaço].

1. [Desmatamento desacelera na Mata Atlântica, mas fragmentação aumenta](https://brasil.mongabay.com/2024/07/desmatamento-desacelera-na-mata-atlantica-mas-fragmentacao-aumenta){target="_blank"}. (2024). Mongabay Brasil.

1. [Consciência ambiental é aceleradora de projetos de restauração na Mata Atlântica](https://umsoplaneta.globo.com/clima/noticia/2024/09/26/consciencia-ambiental-e-aceleradora-de-projetos-de-restauracao-na-mata-atlantica.ghtml){target="_blank"}. (2024). Um Só Planeta.

1. [No Clima dos Biomas: com restauração de florestas e nascentes de água, projetos buscam recuperar uma Mata Atlântica degradada](https://umsoplaneta.globo.com/clima/noticia/2024/09/26/no-clima-dos-biomas-com-restauracao-de-florestas-e-nascentes-de-agua-projetos-buscam-recuperar-uma-mata-atlantica-degradada.ghtml){target="_blank"}. (2024). Um Só Planeta.

1. [O paradoxo da Mata Atlântica](https://piaui.folha.uol.com.br/paradoxo-mata-atlantica-crescimento/){target="_blank"}. (2025). Piauí.

1. [Fragmented Forests Lead to Declining Biodiversity](https://www.climateaction.org/news/fragmented-forests-lead-to-declining-biodiversity){target="_blank"}. (2025). ClimateAction.

1. [Manchas grandes de floresta têm mais biodiversidade do que fragmentos menores somados](https://revistapesquisa.fapesp.br/manchas-grandes-de-floresta-tem-mais-biodiversidade-do-que-fragmentos-menores-somados){target="_blank"}. (2025). Revista Fapesp.

1. [Fragmentação de florestas reduz biodiversidade em todas as escalas, mostra estudo global](https://theconversation.com/fragmentacao-de-florestas-reduz-biodiversidade-em-todas-as-escalas-mostra-estudo-global-252096){target="_blank"}. (2025). The Conversation.

1. [Preservar a biodiversidade exige áreas de conservação amplas](https://www.ecodebate.com.br/2025/03/13/preservar-a-biodiversidade-exige-areas-de-conservacao-amplas){target="_blank"}. (2025). EcoDebate.

1. [Estudo da Nature analisa mais de 4.000 espécies e mostra que é preciso grandes áreas de floresta para preservar diversidade](https://abori.com.br/ambiente/nature-biodiversidade-um/). (2025). bori agência.

1. [Fragmentação florestal e perda de habitat prejudica a biodiversidade](https://www.correiobraziliense.com.br/ciencia-e-saude/2025/03/7082545-fragmentacao-florestal-e-perda-de-habitat-prejudica-a-biodiversidade.html){target="_blank"}. (2025). Correio Braziliense.

1. [Pequenas florestas isoladas não chegam para proteger a biodiversidade](https://greensavers.sapo.pt/pequenas-florestas-isoladas-nao-chegam-para-proteger-a-biodiversidade/){target="_blank"}. (2025). Greensavers.

1. [Para preservar a biodiversidade deve apostar-se nas grandes florestas](https://greensavers.sapo.pt/para-preservar-a-biodiversidade-deve-apostar-se-nas-grandes-florestas/){target="_blank"}. (2025). Greensavers.

1. [Want to preserve biodiversity? Go big, U-M researchers say](https://news.umich.edu/want-to-preserve-biodiversity-go-big-u-m-researchers-say/){target="_blank"}. (2025). Michigan News.

1. [New study refutes habitat fragmentation claim](https://www.idiv.de/new-study-refutes-habitat-fragmentation-claim){target="_blank"}. (2025). IDiv.

1. [Resolving a 50-year debate: fragmentation decreases biodiversity on multiple scales](https://conservationcorridor.org/digests/2025/03/resolving-a-50-year-debate-fragmentation-decreases-biodiversity-on-multiple-scales/){target="_blank"}. (2025). Conservation Corridor.

1. [New paper resolves a half-century old debate about how to conserve biodiversity in natural areas](https://www.anthropocenemagazine.org/2025/03/new-paper-resolves-a-half-century-old-debate-about-how-to-conserve-biodiversity-in-natural-areas/){target="_blank"}. (2025). Anthropocene.

1. [ Em conservação, tamanho é mesmo documento](https://oeco.org.br/noticias/em-conservacao-tamanho-e-mesmo-documento/){target="_blank"}. (2025). oEco.

1. [Conservar a biodiversidade exige grandes áreas florestais e paisagens contínuas](https://jornal.usp.br/ciencias/conservar-a-biodiversidade-exige-grandes-areas-florestais-e-paisagens-continuas/){target="_blank"}. (2025). Jornal da USP.

1. [Mudanças climáticas podem eliminar pequenos mamíferos únicos da Mata Atlântica](https://www.cdslitoralsul.ba.gov.br/Site/Noticias/mudanas-climticas-podem-eliminar-pequenos-mamferos-nicos-da-mata-atlntica-){target="_blank"}. (2025). CDS Litoral Sul.

1. [Mudanças Climáticas Podem Eliminar Pequenos Mamíferos Únicos da Mata Atlântica da América do Sul](https://www2.uesc.br/noticias/1296/Mudancas-Climaticas-Podem-Eliminar-Pequenos-Mamiferos-Unicos-da-Mata-Atlantica-da-America-do-Sul){target="_blank"}. (2025). UESC Notícias.

1. [O que é melhor proteger: grandes florestas ou vários fragmentos? Novo estudo reacende polêmica](https://brasil.mongabay.com/2025/06/o-que-e-melhor-proteger-grandes-florestas-ou-varios-fragmentos-novo-estudo-reacende-polemica){target="_blank"}. (2025). Mongabay.

1. [Protect one large forest, or many small ones? New study reignites conservation debate](https://news.mongabay.com/2025/06/protect-one-large-forest-or-many-small-ones-new-study-reignites-conservation-debate/){target="_blank"}. (2025). Mongabay.

1. [Ganhos de vegetação secundária na Mata Atlântica são insuficientes para compensar perdas de estoque de carbono e áreas de   conservação](https://ufsb.edu.br/ufsb-ciencia/5195-ganhos-de-vegetacao-secundaria-na-mata-atlantica-sao-insuficientes-para-compensar-perdas-de-estoque-de-carbono-e-areas-de-conservacao?utm_source=chatgpt.com){target="_blank"}. (2025). UFSB Ciência.

<style>
#topBtn {
  display: none;
  position: fixed;
  bottom: 105px; /* um pouco acima do fundo */
  left: 50%;
  transform: translateX(-50%);
  padding: 10px 14px;
  font-size: 20px;
  border: none;
  border-radius: 6px;
  background-color: #2381df; 
  color: white;
  cursor: pointer;
  box-shadow: 0 2px 6px rgba(0,0,0,0.3);
  transition: background-color 0.3s;
}
#topBtn:hover {
  background-color: rgba(0, 86, 179, 0.9);
}
</style>

<button id="topBtn" onclick="window.scrollTo({top: 0, behavior: 'smooth'});">↑ Topo</button>

<script>
const btn = document.getElementById("topBtn");

window.addEventListener("scroll", () => {
  const scrollBottom = window.innerHeight + window.scrollY;
  const docHeight = document.documentElement.scrollHeight;

  if (scrollBottom >= docHeight - 200) { // aparece um pouco antes do final
    btn.style.display = "block";
  } else {
    btn.style.display = "none";
  }
});
</script>
